create table task (
    id bigint primary key generated by default as identity,
    done  boolean,
    black_list_id bigint UNIQUE,
    volunteer_id  bigint,
    FOREIGN KEY (black_list_id) REFERENCES black_list(id),
    FOREIGN KEY (volunteer_id) REFERENCES volunteer(id)
);