create  table visitor(
                         id bigint primary key generated by default as identity,
                         chat_id bigint unique not null,
                         firstname varchar(30),
                         lastname varchar(30),
                         username varchar(30),
                         phone_number varchar(30),
                         registered_at timestamp,
                         last_action varchar(255),
                         state varchar(255)
);