create  table visitor(
                         id bigint primary key generated by default as identity,
                         chat_id bigint unique not null,
                         name varchar(255) unique not null,
                         phone_number varchar(30),
                         registered_at date not null,
                         last_action varchar(255)
);