create  table report(
                        id bigint primary key generated by default as identity,
                        date_report timestamp,
                        health_status text,
                        photo oid,
                        bad_report boolean
);