create  table report(
                        id bigint primary key generated by default as identity,
                        chat_id bigint,
                        date_report date,
                        health_status text,
                        file_id varchar(255)
);