create  table report(
                        id bigint primary key generated by default as identity,
                        date date not null,
                        state text,
                        photo oid,
                        bad_report boolean
);