create table pet(
                     id bigint primary key generated by default as identity,
                     name varchar(255) unique not null,
                     adopted boolean not null,
                     date date,
                     report_id bigint constraint report_id references report unique
);
