create table dog(
    id bigint primary key generated by default as identity,
    name varchar(255)  NOT NULL,
    adopted boolean,
    date_adoption date,
    attempt integer default 1,
    test_period integer default 30
);
