create table owner(
                      id bigint primary key generated by default as identity,
                      chat_id bigint unique not null,
                      name varchar(255),
                      registered_at date not null,
                      last_action varchar(255),
                      cat_id bigint constraint cat_id references cat,
                      dog_id bigint constraint dog_id references cat
);
