create table owner(
    id bigint primary key generated by default as identity,
    chat_id bigint NOT NULL UNIQUE ,
    firstname varchar(30),
    lastname varchar(30),
    username varchar(30),
    phone_number varchar(30),
    date_registration date,
    last_action varchar(255),
    registration boolean,
    state varchar(255),
    cat_id bigint,
    dog_id bigint,
    FOREIGN KEY (cat_id) REFERENCES cat(id),
    FOREIGN KEY (dog_id) REFERENCES dog(id)
);
